services:
  - type: web
    name: lumin-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false